### ISSUE TITLE
Picking up after failed assembly jobs?

### ISSUE THREAD

**Issue by halexand** [AlexanderLabWHOI/eukrhythmic#22]
In testing eukrythmic it has occurred to me that different assemblers have different response after breaking. We should think about how to handle this or cover it in the documentation. 

For example:
- Trinity: after breaking (running out of memory, time limit, etc.) you can just reinitialize trinity command with the same output directory that was specified in the original script and it will pickup at the last checkpoint. 
- Megahit: after breaking it also has a checkpoint/continue option but it needs to be specified in the command (i.e. `--continue`) otherwise if restarted it will throw an error if the output directory is not empty. 

Not so much an issue as a "we should figure out how to handle re-starting assemblers" issue. @akrinos @cnatalie

**Comment by akrinos** [comment]
We should pay attention to this for future assemblers, but seems fixed at the moment
