### ISSUE TITLE
Strange behavior with `megahit` rule

### ISSUE THREAD

**Issue by halexand** [AlexanderLabWHOI/eukrhythmic#30]
Megahit is making a directory each time in the `eukrhythmic` main directory (/`vortexfs1/omics/alexander/halexander/eukrhythmic/megahit`)  even though it isn't specified in the `config.yaml` file. It appears to be also running the SE rule even though it is not an unpaired read. 

These are the options from the megahit folder run (which completed) in the eukrythmic directory: 
```
{"out_dir": "/vortexfs1/omics/alexander/halexander/eukrhythmic/megahit", "temp_dir": "/vortexfs1/omics/alexander/halexander/eukrhythmic/megahit/tmp", "test_mode": false, "continue_mode": false, "force_overwrite": false, "memory": 0.9, "min_contig_len": 200, "k_min": 21, "k_max": 111, "k_step": 10, "k_list": [21, 31, 41, 51, 61, 71, 81, 91, 101, 111], "auto_k": false, "set_list_by_min_max_step": true, "min_count": 2, "has_popcnt": true, "hw_accel": true, "max_tip_len": -1, "no_mercy": false, "no_local": false, "bubble_level": 2, "merge_len": 20, "merge_similar": 0.95, "prune_level": 2, "prune_depth": 2, "num_cpu_threads": 8, "disconnect_ratio": 0.1, "low_local_ratio": 0.2, "cleaning_rounds": 5, "keep_tmp_files": false, "mem_flag": 1, "out_prefix": "", "kmin_1pass": false, "pe1": [], "pe2": [], "pe12": [], "se": ["/vortexfs1/omics/alexander/halexander/NB-eukrythmic/firsttrim/SRR1810207_1.trimmed.fastq.gz"], "presets": "", "verbose": false}
```

 It is also failing and calling an error because the

**Comment by halexand** [comment]
Kind of a strange bug. I can't figure it out...

**Comment by akrinos** [comment]
Writing to `megahit` in current directory is a typo...that's how it's specified in the `megahit` module. Extra `-o megahit` that shouldn't be there. Not sure when it got changed, but then propagated to all of the additional commands due to copy/paste probably. Fixed that part. It's possible the second problem is due to the output file not being found using PE.
