### ISSUE TITLE
metaT sample file naming

### ISSUE THREAD

**Issue by cnatalie** [AlexanderLabWHOI/eukrhythmic#35]
metaT file does not handle "_" in sample file name. Example:

HN001_S1 works
HN001 does not - results in float/string error 

actual sample file name: HN001_S1_L002_R1_001.fastq.gz

**Comment by akrinos** [comment]
Do you mean that HN001 works, but HN001_S1 does not, @cnatalie?

**Comment by cnatalie** [comment]
Sorry! HN001 and HN001_S1 as both work as SampleNames with that raw file. Here is an example of one that does not:

C47M_47 - works
C47M  - does not:
 ```
TypeError in line 15 of /nas/longleaf/home/cnatalie/eukrhythmic/Snakefile:
must be str, not float
```

Sample file name: C47M_47_R1_001.fastq.gz

metaT file:
SampleName      SampleID        AssemblyGroup   FastqFile
C47M C47M C47M C47M
C32M C32M C32M C32M

**Comment by akrinos** [comment]
This was resolved in the following way: the fastqfile name should be different, in this case, because it doesn't include enough of the file name. In the future, this file should be simplified/not required for users to supply.
