### ISSUE TITLE
Couple things

### ISSUE THREAD

**Issue by cnatalie** [AlexanderLabWHOI/eukrhythmic#78]
- Snakemake requires a spikefile to be defined in _config.yaml_, even if not using one (runbbmap=0):

`Check that you have specified values in the configuration file. The missing entry that triggered this error was spikefile.`

- Snakemake looks for _no_rrna_removal_step0_ rule input (Is there a ribodetector rule?): 

```
MissingInputException in rule no_rrna_removal_step0 in file /proj/omics/alexander/collab/2024-metaT-intercal/eukrhythmic/eukrhythmic, line 129:
Missing input files for rule no_rrna_removal_step0:
```

- extra space in "/proj/omics/alexander/collab/2024-metaT-intercal/eukrhythmic/rules/02-trim.smk", line 73

`SyntaxError: unexpected character after line continuation character`

- The _snake-submit.sh_ cluster arguments are not recognized with Snakemake 8.10.8:

`snakemake: error: unrecognized arguments: --cluster-config`

**Comment by akrinos** [comment]
@cnatalie w.r.t. point 2 on `no_rrna_removal_step0` - this would indicate that you're running eukrhythmic without the RiboDetector rule. Adding `removerrna: 1` to the configuration file adds this requirement. The error you're showing is related to the input of one of the status files. Can you provide the rest of the error?

With respect to Snakemake 8.10.8, that's a bigger problem - several things need to be changed to make eukrhythmic compatible with the newer version of Snakemake

**Comment by cnatalie** [comment]
Thanks! I see the ribodetector rule now, and it looks like snakemake disabled cluster configuration after version 8
